<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Menu successful updated' => 'Меню успешно обновлено',
    'Name' => 'Название',
    'Update link: {name}' => 'Редактирование ссылки: {name}',
    'Update menu: {name}' => 'Редактирование меню: {name}',
    'Active' => 'Активность',
    'Create link - {name}' => 'Добавить ссылку - {name}',
    'Create menu link' => 'Добавить ссылку',
    'Display order' => 'Порядок отображения',
    'ID' => 'ИД',
    'Label' => 'Текст ссылки',
    'Levels' => 'Уровни',
    'Link' => 'Ссылка',
    'Link successful created' => 'Ссылка успешно создана',
    'Link successful deleted' => 'Ссылка успешно удалена',
    'Link successful updated' => 'Ссылка успешно обновлена',
    'Site menu' => 'Меню сайта',
];
